### ISSUE TITLE
Is it possible to make a rule with mpd plugin ?

### ISSUE THREAD

**Issue by fipsman** [pimatic/pimatic-mpd#1]
i would like to make a rule that at 7am  mpd starts .
How can i do that ?
if its 7am then ......???

**Comment by fipsman** [comment]
@Tom-Jans &  sweetpi 
works like a charm. Waking up now to music and lights !!
thanks a lot !
Is it normal though  that the music stops after half a minute ?
Can i change that ? i would like that mpd starts and keeps playing until i stop it !

**Comment by Tom-Jans** [comment]
Never had the problem about music stopping after half a minute. Maybe you got a rule that does that or the problem is with your mpd player.

**Comment by sweetpi** [comment]
I've the problem if I play streaming urls (web radio) with mpd. I think it uses the buffer from the previous session when starting playing and stops when the buffer is empty. As a work around I press first "next" and then "play" and then it works.
