### ISSUE TITLE
ambiguous action

### ISSUE THREAD

**Issue by quantenschaum** [pimatic/pimatic-mpd#8]
If I try to define a rule

    if 12:00 then play mpd-player

I get the error message "next action of 'play mpd-player' is ambiguous".

I expect the action send a play command to the mpd, so that it starts playing the queue where it was left when it was stopped. What is wrong here?

The rule

    if 12:00 then stop mpd-player

can be created and works as expected.

**Comment by quantenschaum** [comment]
workaround: use pimatic-shell-execute plugin and

    if 12:00 then execute "mpc play"

pimatic-mpd will pick up the state change correctly

**Comment by sweetpi** [comment]
Should be fixed when https://github.com/Fjuxx/pimatic-kodi/pulls gets published.

**Comment by Xento** [comment]
I have the same problem but with stop mpd-player.

**Comment by Xento** [comment]
Is this issue fixed now?

**Comment by sweetpi** [comment]
Sorry still waiting for @Fjuxx to transfer the ownship of the npm package. I created a new issue for that (https://github.com/Fjuxx/pimatic-kodi/issues/9) If there is no response till end of this month, then I will create a new npm package with a different name and inform you.

**Comment by sweetpi** [comment]
I justed published the update for the pimatic-kodi package. So the error should be gone.
